version: "2"

services:

  samba:
    image: dperson/samba:rpi
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:130
      - 445:445
    volumes:
      - /usr/share/zoneinfo/America/Argentina/Mendoza:/etc/localtime
      - ${MEDIA}:/media
      - ${DOWNLOADS}:/downloads

  rtorrent:
    image: linuxserver/rutorrent:arm32v7-v3.9-ls47
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80:80
      - 51413:51413
      - 6881:6881/udp
    volumes:
      - ${TORRENTS_CONFIG}:/config
      - ${MEDIA}:${MEDIA}
      - ${DOWNLOADS}:/downloads
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  plex:
    image: jaymoulin/plex:1.16.3-armhf
    ports:
      - 32400:32400
      - 33400:33400
    volumes:
      - ${PLEX_CONFIG}:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
    restart: always
    network_mode: "host"
