version: "3.7"

services:

  samba:
    image: dperson/samba # no hay tag con versiones, solo latest
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=America/Argentina/Mendoza
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads

  plex:
    image: jaymoulin/plex:1.30.1.6562
    expose:
      - 32400
      - 33400
    # Descomentar si NO usas network_mode: "host"
    # ports:
    #  - 32400:32400
    #  - 33400:33400
    environment:
      - TZ=America/Argentina/Mendoza
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host" # Solo funciona en Linux

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.5
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - PUID=1001
      - PGID=1001
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=p3l4d0_N3RD # la puedes cambiar por la que quieras
    restart: unless-stopped
